"""Domain models for the negotiation prototype."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import Any, Literal


AgentRole = Literal["buyer", "seller"]


@dataclass(frozen=True)
class Scenario:
    """Controlled supply-chain scenario with hard bounds and preferences."""

    scenario_id: str
    description: str
    min_unit_price: float
    max_unit_price: float
    min_quantity: int
    max_quantity: int
    earliest_delivery_deadline: date
    latest_delivery_deadline: date
    buyer_target_unit_price: float
    buyer_target_quantity: int
    buyer_target_delivery_deadline: date
    seller_target_unit_price: float
    seller_target_quantity: int
    seller_target_delivery_deadline: date


@dataclass(frozen=True)
class Offer:
    """Offer generated by one negotiation agent."""

    agent_role: AgentRole
    unit_price: float
    quantity: int
    delivery_deadline: date


@dataclass(frozen=True)
class Agreement:
    """Agreement terms accepted by both agents."""

    unit_price: float
    quantity: int
    delivery_deadline: date
    reached_at_round: int


@dataclass(frozen=True)
class TurnLog:
    """Structured record of one agent turn."""

    round_number: int
    agent_role: AgentRole
    offer: Offer
    is_valid: bool
    errors: tuple[str, ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class NegotiationResult:
    """Final outcome of a negotiation run."""

    scenario: Scenario
    max_rounds: int
    agreement: Agreement | None
    turn_log: tuple[TurnLog, ...]
    stopped_reason: str

    @property
    def agreement_reached(self) -> bool:
        """Return whether an agreement was reached."""

        return self.agreement is not None


JsonDict = dict[str, Any]
